#!/bin/bash
# Quick test for issue detail navigation

echo "Testing Issue Detail Navigation Fix"
echo ""
echo "This test verifies that:"
echo "1. Issue list displays correctly with #IID format"
echo "2. Pressing <Enter> on an issue line opens the detail view"
echo ""

# Check TypeScript syntax
echo "Checking TypeScript syntax..."
deno check denops/gitxab/main.ts 2>&1 | grep -i error || echo "✓ No critical errors"

echo ""
echo "=== Manual Test Instructions ==="
echo ""
echo "1. Start Neovim and run:"
echo "   :GitXabIssues 278964"
echo ""
echo "2. You should see lines like:"
echo "   #580907 Issue title [labels] @username date"
echo ""
echo "3. Move cursor to any issue line and press <Enter>"
echo ""
echo "4. Expected: Issue detail view opens showing:"
echo "   - Issue #IID: Title"
echo "   - Full description"
echo "   - Comments"
echo ""
echo "5. In issue detail, try these keys:"
echo "   c - Add comment (will prompt for text)"
echo "   e - Edit issue (shows menu)"
echo "   r - Refresh view"
echo "   q - Close"
echo ""
echo "If <Enter> doesn't work, check:"
echo "- Are you on a line starting with #IID?"
echo "- Does :messages show any errors?"
