-- GitXab.vim - Denops-based GitLab integration plugin
-- This file is intentionally minimal - the actual plugin logic is in:
-- - autoload/gitxab.vim (Vim script for command definitions)
-- - denops/gitxab/main.ts (TypeScript for GitLab API logic)
